### ISSUE TITLE
RX Codes

### ISSUE THREAD

**Issue by SodyFX** [argilo/secplus#10]
I may be missing the mark entirely here. When running ./secplus_rx.py I get the flow graph, but no other outputs. What is the method to retrieve the bits to decode from the flow graph as it seems the sample data is just the graph and nothing is output beyond that.

Small side note, could a C1101 be used to transmit or must an SDR be used?

I'm attempting to create a RPi touchscreen device to open my garage and gates.

**Comment by argilo** [comment]
> What is the method to retrieve the bits to decode from the flow graph

Received packets are printed at the console like so:
```
Security+ 2.0:  rolling=240124948  fixed=70678577664  (button=16 remote_id=1959100928)
Security+ 2.0:  rolling=240124949  fixed=70678577664  (button=16 remote_id=1959100928)
```

> could a C1101 be used to transmit

I expect so, but this is not supported out of the box. You could generate on-off keying sequences using the `encode_ook` (Security+) or `encode_v2_manchester` (Security+ 2.0) functions in the `secplus` module, and then you'd need to configure the CC1101 to transmit them on the right frequency and at the right speed.

**Comment by rootabeta** [comment]
Seconding this issue - I'm using a HackRF One, firmware 2021.03.1. No output to stdout, but I get the qwt UI.

**Comment by argilo** [comment]
I'll close this issue off since I haven't heard anything back, and receive appears to be working correctly.
