### ISSUE TITLE
How to use on a non GUI platform?

### ISSUE THREAD

**Issue by ksaye** [argilo/secplus#13]
Reading your documentation, it shows to be all command line but the commands seems to have changed to be all GUI, as shown below:

![image](https://user-images.githubusercontent.com/15837044/210111486-e4d5ab73-c1e9-48fc-8013-da6628b2b7cd.png)

How can I use this with a non GUI platform?  If I run it with X11 forwarding disabled, I get a core dump:

![image](https://user-images.githubusercontent.com/15837044/210111561-e690ba64-5e46-453c-a85f-e45fca7644d7.png)

**Comment by argilo** [comment]
If you don't want the GUI elements, you'll have to open up the GNU Radio flowgraph (`secplus_rx.grc`) in GNU Radio Companion, remove the GUI elements, and switch to "No GUI" mode in the Options block.

**Comment by argilo** [comment]
You might also be able to coax the existing version to run with the following command:

`QT_QPA_PLATFORM=offscreen ./secplus_rx.py`

**Comment by ksaye** [comment]
Thanks, that did it!

> ksaye@up1:/opt/gdoor/secplus$ QT_QPA_PLATFORM=offscreen ./secplus_rx.py
> Warning: failed to XInitThreads()
> Unable to init server: Could not connect: Connection refused
> Unable to init server: Could not connect: Connection refused
> 
> (secplus_rx.py:6134): Gdk-CRITICAL **: 21:28:40.715: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
> gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.10.5.0
> built-in source types: file rtl rtl_tcp rfspace redpitaya 
> Using device #0 Realtek RTL2838UHIDIR SN: 00000001
> Found Rafael Micro R820T tuner
> [R82XX] PLL not locked!
> Exact sample rate is: 2000000.052982 Hz
> [R82XX] PLL not locked!
> This plugin does not support propagateSizeHints()
> OOOOOOOOOOOOOOOOOOOOOOSecurity+:  rolling=92  fixed=455XXXX035  (id1=0 id0=0 switch=0 pad_id=0 pin=7715)
