### ISSUE TITLE
Secplus for 433Mhz?

### ISSUE THREAD

**Issue by KjellKriminell6** [argilo/secplus#20]
hi!
I would like to use 433Mhz in Europe.
Would that be possible?
thanks!

**Comment by argilo** [comment]
Yes. Open secplus_rx.grc in gnuradio-companion, then edit the frequency list in the "QT GUI Chooser" block. Then press the Run button to execute the modified flow graph.

**Comment by argilo** [comment]
If 433 MHz works, let me know the exact frequency and I can add it into the program for everyone.

**Comment by KjellKriminell6** [comment]
Thanks for your reply!

It works fine changing the QT GUI Chooser.
But when trying to execute, I get an error saying "secplus_decode   Param 'Code'   Can't interpret source code: No module named secplus"

**Comment by argilo** [comment]
Make sure you execute `secplus_rx.py` from the project's root directory (i.e. the directory containing secplus.py).

**Comment by argilo** [comment]
If you start `gnuradio-companion` from the command line while in the project's root directory, it will probably work in GRC as well.

**Comment by KjellKriminell6** [comment]
No, sorry, starting gnuradio-companion in CLI in projects root folder did not erase the errors mentioned above.

I would really like to try this script at 433,92Mhz, can you add that frequency please?

**Comment by KjellKriminell6** [comment]
Thanks a lot, that worked out great adjusting it to 433,92MHz!
Keep up the good work!

**Comment by argilo** [comment]
Were you able to decode any remotes at that frequency? If so I'd be curious to know what the model numbers are.

**Comment by iihyefar** [comment]
> Were you able to decode any remotes at that frequency? If so I'd be curious to know what the model numbers are.

Should be any liftmaster/Chamberlain product with security 2.0 (yellow learn button)

**Comment by argilo** [comment]
Fixed in 00dccc36a041c82ce2eaa64cbdc89a556432669b.
