### ISSUE TITLE
Protocol Question: Rollover

### ISSUE THREAD

**Issue by Crsarmv7l** [argilo/secplus#21]
Is the entirety of the rolling piece the count? Its not right? I am trying to get a better understanding of the components in the rolling part to prevent an overflow when incrementing the count.

For instance with Keeloq there are also two pieces; the fixed comprised of 8 hex digits, and the rolling part which is also 8 hex digits; however of the rolling part, only the last 4 hex digits are the count. So ignoring overflow bits, the keeloq count rolls over after FFFF.

**Comment by argilo** [comment]
As far as I know, the entire rolling code is a single count.

**Comment by Crsarmv7l** [comment]
> As far as I know, the entire rolling code is a single count.

Alright. I figure I might as well test the limits and see if it still works on my garage door, eg with 0xFFFFFFFF and 0x00000002
